[2025-02-04T09:37:08.672+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T09:37:08.698+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_workflow.full_transform manual__2025-02-04T09:36:59.718690+00:00 map_index=0 [queued]>
[2025-02-04T09:37:08.709+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_workflow.full_transform manual__2025-02-04T09:36:59.718690+00:00 map_index=0 [queued]>
[2025-02-04T09:37:08.709+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-04T09:37:08.718+0000] {taskinstance.py:2889} INFO - Executing <Mapped(_PythonDecoratedOperator): full_transform> on 2025-02-04 09:36:59.718690+00:00
[2025-02-04T09:37:08.727+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=219) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-04T09:37:08.728+0000] {standard_task_runner.py:72} INFO - Started process 230 to run task
[2025-02-04T09:37:08.729+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_workflow', 'full_transform', 'manual__2025-02-04T09:36:59.718690+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpj2c9xspr', '--map-index', '0']
[2025-02-04T09:37:08.730+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask full_transform
[2025-02-04T09:37:08.774+0000] {task_command.py:467} INFO - Running <TaskInstance: test_workflow.full_transform manual__2025-02-04T09:36:59.718690+00:00 map_index=0 [running]> on host bcbdac0c6b51
[2025-02-04T09:37:08.874+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_workflow' AIRFLOW_CTX_TASK_ID='full_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T09:36:59.718690+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T09:36:59.718690+00:00'
[2025-02-04T09:37:08.875+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-04T09:37:08.876+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-04T09:37:08.876+0000] {logging_mixin.py:190} INFO - Current task name:full_transform state:running start_date:2025-02-04 09:37:08.699296+00:00
[2025-02-04T09:37:08.876+0000] {logging_mixin.py:190} INFO - Dag name:test_workflow and current dag run status:running
[2025-02-04T09:37:08.876+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T09:37:08.900+0000] {logging_mixin.py:190} INFO - shape: (5, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────┬─────────────┬───────────┬─────────────┐
│ id      ┆ variant_id ┆ body_type ┆ city      ┆ … ┆ make  ┆ model       ┆ gear      ┆ owner       │
│ ---     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---   ┆ ---         ┆ ---       ┆ ---         │
│ i32     ┆ i32        ┆ str       ┆ str       ┆   ┆ str   ┆ str         ┆ str       ┆ str         │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════╪═════════════╪═══════════╪═════════════╡
│ 4345291 ┆ 7528       ┆ SUV       ┆ Bangalore ┆ … ┆ Volvo ┆ Volvo XC60  ┆ Automatic ┆ second-owne │
│         ┆            ┆           ┆           ┆   ┆       ┆             ┆           ┆ r           │
│ 4337692 ┆ 6502       ┆ SUV       ┆ Bangalore ┆ … ┆ Volvo ┆ Volvo XC40  ┆ Automatic ┆ fourth-owne │
│         ┆            ┆           ┆           ┆   ┆       ┆             ┆           ┆ r           │
│ 4328557 ┆ 5540       ┆ Hatchback ┆ Bangalore ┆ … ┆ Volvo ┆ Volvo V40   ┆ Automatic ┆ third-owner │
│         ┆            ┆           ┆           ┆   ┆       ┆ Cross       ┆           ┆             │
│         ┆            ┆           ┆           ┆   ┆       ┆ Country     ┆           ┆             │
│ 4327070 ┆ 5500       ┆ Sedan     ┆ Bangalore ┆ … ┆ Volvo ┆ Volvo S90   ┆ Automatic ┆ second-owne │
│         ┆            ┆           ┆           ┆   ┆       ┆             ┆           ┆ r           │
│ 4318504 ┆ 2061       ┆ Sedan     ┆ Bangalore ┆ … ┆ Volvo ┆ Volvo S60   ┆ Automatic ┆ second-owne │
│         ┆            ┆           ┆           ┆   ┆       ┆             ┆           ┆ r           │
└─────────┴────────────┴───────────┴───────────┴───┴───────┴─────────────┴───────────┴─────────────┘
[2025-02-04T09:37:08.901+0000] {python.py:240} INFO - Done. Returned value was: shape: (11, 11)
┌─────────┬────────────┬───────────┬────────────┬───┬───────┬─────────────┬───────────┬────────────┐
│ id      ┆ variant_id ┆ body_type ┆ city       ┆ … ┆ make  ┆ model       ┆ gear      ┆ owner      │
│ ---     ┆ ---        ┆ ---       ┆ ---        ┆   ┆ ---   ┆ ---         ┆ ---       ┆ ---        │
│ i32     ┆ i32        ┆ str       ┆ str        ┆   ┆ str   ┆ str         ┆ str       ┆ str        │
╞═════════╪════════════╪═══════════╪════════════╪═══╪═══════╪═════════════╪═══════════╪════════════╡
│ 4345291 ┆ 7528       ┆ SUV       ┆ Bangalore  ┆ … ┆ Volvo ┆ Volvo XC60  ┆ Automatic ┆ second-own │
│         ┆            ┆           ┆            ┆   ┆       ┆             ┆           ┆ er         │
│ 4337692 ┆ 6502       ┆ SUV       ┆ Bangalore  ┆ … ┆ Volvo ┆ Volvo XC40  ┆ Automatic ┆ fourth-own │
│         ┆            ┆           ┆            ┆   ┆       ┆             ┆           ┆ er         │
│ 4328557 ┆ 5540       ┆ Hatchback ┆ Bangalore  ┆ … ┆ Volvo ┆ Volvo V40   ┆ Automatic ┆ third-owne │
│         ┆            ┆           ┆            ┆   ┆       ┆ Cross       ┆           ┆ r          │
│         ┆            ┆           ┆            ┆   ┆       ┆ Country     ┆           ┆            │
│ 4327070 ┆ 5500       ┆ Sedan     ┆ Bangalore  ┆ … ┆ Volvo ┆ Volvo S90   ┆ Automatic ┆ second-own │
│         ┆            ┆           ┆            ┆   ┆       ┆             ┆           ┆ er         │
│ 4318504 ┆ 2061       ┆ Sedan     ┆ Bangalore  ┆ … ┆ Volvo ┆ Volvo S60   ┆ Automatic ┆ second-own │
│         ┆            ┆           ┆            ┆   ┆       ┆             ┆           ┆ er         │
│ …       ┆ …          ┆ …         ┆ …          ┆ … ┆ …     ┆ …           ┆ …         ┆ …          │
│ 4311504 ┆ 7535       ┆ SUV       ┆ Bangalore  ┆ … ┆ Volvo ┆ Volvo XC40  ┆ Automatic ┆ first-owne │
│         ┆            ┆           ┆            ┆   ┆       ┆             ┆           ┆ r          │
│ 4304279 ┆ 5500       ┆ Sedan     ┆ Chandigarh ┆ … ┆ Volvo ┆ Volvo S90   ┆ Automatic ┆ first-owne │
│         ┆            ┆           ┆            ┆   ┆       ┆             ┆           ┆ r          │
│ 4298057 ┆ 2092       ┆ SUV       ┆ Bangalore  ┆ … ┆ Volvo ┆ Volvo XC40  ┆ Automatic ┆ first-owne │
│         ┆            ┆           ┆            ┆   ┆       ┆             ┆           ┆ r          │
│ 4293686 ┆ 2085       ┆ SUV       ┆ Bangalore  ┆ … ┆ Volvo ┆ Volvo XC 90 ┆ Automatic ┆ first-owne │
│         ┆            ┆           ┆            ┆   ┆       ┆             ┆           ┆ r          │
│ 4279387 ┆ 2072       ┆ Sedan     ┆ Bangalore  ┆ … ┆ Volvo ┆ Volvo S60   ┆ Automatic ┆ first-owne │
│         ┆            ┆           ┆            ┆   ┆       ┆             ┆           ┆ r          │
└─────────┴────────────┴───────────┴────────────┴───┴───────┴─────────────┴───────────┴────────────┘
[2025-02-04T09:37:08.909+0000] {xcom.py:690} ERROR - Object of type bytes is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-02-04T09:37:08.910+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3639, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-02-04T09:37:08.923+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T09:37:08.923+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 09:37:08.699296+00:00 end:2025-02-04 09:37:08.923007+00:00 duration:0.223711
[2025-02-04T09:37:08.924+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): full_transform> dag:<DAG: test_workflow> dagrun:<DagRun test_workflow @ 2025-02-04 09:36:59.718690+00:00: manual__2025-02-04T09:36:59.718690+00:00, state:running, queued_at: 2025-02-04 09:36:59.730805+00:00. externally triggered: True>
[2025-02-04T09:37:08.924+0000] {logging_mixin.py:190} INFO - Failure caused by Object of type bytes is not JSON serializable
[2025-02-04T09:37:08.924+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test_workflow, task_id=full_transform, run_id=manual__2025-02-04T09:36:59.718690+00:00, map_index=0, execution_date=20250204T093659, start_date=20250204T093708, end_date=20250204T093708
[2025-02-04T09:37:08.932+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T09:37:08.932+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task full_transform (Object of type bytes is not JSON serializable; 230)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3639, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-02-04T09:37:08.942+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-04T09:37:08.960+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T09:37:08.961+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
